[package]
name = "jinjerbread"
version = "0.1.0"
authors = ["kenkoooo <kenkou.n@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"
chrono-tz = "0.5"

[[bin]]
name = "change_status"
path = "./example/change_status.rs"
